sudo: false
language: node_js
node_js:
  - 4
  - 6
  - 8
  - 9

env:
  global:
  global:
  - SAUCE_USERNAME: karmarunnerbot
  - secure: "bRVY+hYZwMf1SqVnMyZRJTLD0gN1hLx9/MwO8MM/qBiu3YNjXy49XElfMdzMKN6cZeKTmhcnjmZonbJuI1PQ2t+utGkyjnlVLJ/OlWptreKLzIlcbt4hrdPoTcjmUTwDWq9Ex9cVoYX8AzCasETttpczp3P+s3+vmOUj8z25JyU="
  - CXX=g++-4.8

# Make sure we have new NPM.
before_install:
  - if [[ "`node --version`" = v4* ]]; then npm install -g npm@latest-3; fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export $(openssl aes-256-cbc -pass env:CREDENTIALS_PASS -d -in credentials)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - ./run.sh karma@latest
